### ISSUE TITLE
Mismatch between readme for 1.20.1 modpacks and what is shipped for Prominence

### ISSUE THREAD

**Issue by CommanderTso** [chorbintime/LPS-readme#2]
Hi,

I'm running a Prominence 2 server and was looking for current advice on which Java installation to us.  The [1.20.1 wiki page](https://github.com/chorbintime/LPS-readme/wiki/1.20.1) notes that Java 21 is required to host 1.20.1 modpacks, but currently Prom2 is shipping with a variables.txt using Java 17.

Assuming that the Prom2 project doesn't plan to upgrade to Java 21 any time soon, this is a mismatch. I know it seems like a minor item, but because of the disagreement, it makes me leery of upgrading to Java 21 for my server because I don't know if other portions of the wiki page are incorrect as applies to Prom2.

Thanks!

**Comment by chorbintime** [comment]
Use java 21. The variables.txt is currently outdated
